# name: useHotel-Frontend

# on:
#   push:
#     branches:
#       - main
# env:
#   VITE_USEHOTEL_BACKEND: ${{ secrets.VITE_USEHOTEL_BACKEND }}
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     timeout-minutes: 10
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           path: |
#             public
#             .cache
#             node_modules
#           key: ${{ runner.os }}-gatsby-alexhyett-site-build-${{ github.run_id }}
#           restore-keys: |
#             ${{ runner.os }}-gatsby-alexhyett-site-build-
#       - name: Install dependencies
#         run: yarn
#       - name: Build
#         run: yarn run build
#       - name: Set AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-northeast-1
#       - name: Delete previous build
#         run: aws s3 rm s3://usehotelfrontend --recursive
#       - name: Deploy to S3
#         run: aws s3 sync dist/ s3://usehotelfrontend
